application: emojify-185414
version: 1
runtime: php55
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?\..*$
- ^(.*/)?-.*$

handlers:
#- url: /createRules/?
#  script: /createRules/createRules.php
- url: .*
  script: main.php